[package]
name = "extreme"
version = "0.1.0"
authors = ["Jean-Eudes"]

[dependencies]
rustc-serialize = "0.3"

[dependencies.nickel]
version = "*"
# If you are using the 'nightly' rust channel you can uncomment
# the line below to activate unstable features
# features = ["unstable"]

